language: ruby
rvm:
  - 2.2.7

# branch whitelist
branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-html --allow-hash-href --url-ignore '/.*www.linkedin.com.*/'

notifications:
  email: true
