include: 
 - docs

plugins:
 - jekyll-remote-theme

remote_theme: Labs64/NetLicensing-Wiki-template

logo: "/assets/images/LogoLabs64_2D_S.png"

# Enable or disable the site search
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "NetLicensing Website":
    - "//netlicensing.io"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2013 <a href=\"https://www.labs64.com\">Labs64 GmbH</a>"

# Google Analytics Tracking
ga_tracking: UA-32654174-2
