version: '3'
services:
  netlicensing-wiki:
    image: jekyll/jekyll:pages
    container_name: NetLicensing-Wiki
    volumes:
      - "./docs:/srv/jekyll"
    working_dir: /srv/jekyll
    command: bash -c "gem install webrick && jekyll serve --watch --incremental --verbose --drafts --future --config _config.yml"
    ports:
      - "4000:4000"
